export const characterSchema = {
    type: 'object',
    required: ['nome', 'raca', 'classe', 'nivel', 'atributos'],
    properties: {
        nome: { type: 'string', minLength: 1, maxLength: 100 },
        raca: { type: 'string', minLength: 1, maxLength: 50 },
        classe: { type: 'string', minLength: 1, maxLength: 50 },
        nivel: { type: 'integer', minimum: 1, maximum: 20 },
        background: { type: 'string', maxLength: 100 },
        alinhamento: { type: 'string', maxLength: 50 },
        aparencia: { type: 'string', maxLength: 500 },
        personalidade: { type: 'string', maxLength: 500 },
        atributos: {
            type: 'object',
            required: ['forca', 'destreza', 'constituicao', 'inteligencia', 'sabedoria', 'carisma'],
            properties: {
                forca: { type: 'integer', minimum: 1, maximum: 30 },
                destreza: { type: 'integer', minimum: 1, maximum: 30 },
                constituicao: { type: 'integer', minimum: 1, maximum: 30 },
                inteligencia: { type: 'integer', minimum: 1, maximum: 30 },
                sabedoria: { type: 'integer', minimum: 1, maximum: 30 },
                carisma: { type: 'integer', minimum: 1, maximum: 30 },
            },
            additionalProperties: false,
        },
        habilidades: { type: 'array', items: { type: 'string' }, maxItems: 20 },
        magias: { type: 'array', items: { type: 'string' }, maxItems: 50 },
        equipamentos: { type: 'array', items: { type: 'string' }, maxItems: 30 },
        historia: { type: 'string', maxLength: 2000 },
        pontos_de_vida: { type: 'integer', minimum: 1 },
        classe_armadura: { type: 'integer', minimum: 1 },
    },
    additionalProperties: false,
} as const;
